CREATE SEQUENCE clients_seq START WITH 1;

CREATE OR REPLACE TRIGGER CLIENTS_PK_INCREMENT 
BEFORE INSERT ON Suli.CLIENTS 
FOR EACH ROW

BEGIN
  SELECT pk_clients.NEXTVAL
  INTO   :new.CLIENT_ID
  FROM   dual;
END;


CREATE SEQUENCE cars_seq START WITH 0;

CREATE OR REPLACE TRIGGER CAR_PK_INCREMENT 
BEFORE INSERT ON CARS 
FOR EACH ROW

BEGIN
  SELECT CLIENT_SEQ.NEXTVAL
  INTO   :new.CLIENT_ID
  FROM   dual;
END;

CREATE SEQUENCE parts_seq START WITH 1;

CREATE OR REPLACE TRIGGER PARTS_PK_INCREMENT 
BEFORE INSERT ON PARTS 
FOR EACH ROW

BEGIN
  SELECT CLIENT_SEQ.NEXTVAL
  INTO   :new.PART_ID
  FROM   dual;
END;

CREATE SEQUENCE services_seq START WITH 1;

CREATE OR REPLACE TRIGGER SERVICES_PK_INCREMENT 
BEFORE INSERT ON SERVICES 
FOR EACH ROW

BEGIN
  SELECT SERVICES_SEQ.NEXTVAL
  INTO   :new.SERVICE_ID
  FROM   dual;
END;

CREATE SEQUENCE worksheets_seq START WITH 1;

CREATE OR REPLACE TRIGGER WORKSHEETS_PK_INCREMENT 
BEFORE INSERT ON WORKSHEETS 
FOR EACH ROW

BEGIN
  SELECT WORKSHEETS_SEQ.NEXTVAL
  INTO   :new.WORKSHEET_ID
  FROM   dual;
END;


		
